### ISSUE TITLE
unknown receiver 'SplashScreen'

### ISSUE THREAD

**Issue by stephenkopylov** [crazycodeboy/react-native-splash-screen#280]
Hello! 
I'm getting this error on stable build of lib:

`node_modules/react-native-splash-screen/ios/RNSplashScreen.m:52:6: unknown receiver 'SplashScreen'; did you mean 'RNSplashScreen'?`

**Comment by jurajkrivda** [comment]
Same issue here

**Comment by ketoiloihp** [comment]
See on: https://github.com/crazycodeboy/react-native-splash-screen/blob/master/ios/RNSplashScreen.m

```
+ (void) jsLoadError:(NSNotification*)notification
{
    // If there was an error loading javascript, hide the splash screen so it can be shown.  Otherwise the splash screen will remain forever, which is a hassle to debug.
    [RNSplashScreen hide];
}

RCT_EXPORT_METHOD(hide) {
    [RNSplashScreen hide];
}

RCT_EXPORT_METHOD(show) {
    [SplashScreen show];
}
```
All the function using `RNSplashScreen` but the last function `RCT_EXPORT_METHOD` still using  `SplashScreen` instead of `RNSplashScreen`. Pls correct it on the `master` branch

**Comment by John231** [comment]
I had the same issue too and it seems to be a typo in the RNSplashScreen.m file on line 52. The interface exports an object named RNSplashScreen instead of SplashScreen. If you edit line to be `[RNSplashScreen show];` this should solve your compilation issues.

https://github.com/crazycodeboy/react-native-splash-screen/blob/2b96a49e3650daf7d732d3195005877034420a22/ios/RNSplashScreen.m#L52

**Comment by pontusab** [comment]
Install `react-native-splash-screen:  3.0.9` for now.
