### ISSUE TITLE
White splash screen

### ISSUE THREAD

**Issue by IceNeoMax** [crazycodeboy/react-native-splash-screen#36]
i did exactly the same thing. everything seems alright till i get a totally blank splash screen.
can anyone explains why?

**Comment by YasirPanjsheri** [comment]
@IceNeoMax hi, I am having the same problem with iOS , I get white screen. How did you solve the problem?

**Comment by jstansbe** [comment]
Not sure why this was closed... so is there a solution?
@YasirSherzad as a workaround i just changed the background color to match what my first React-Native screen has. 

example: instead of a white screen "flashing" have a blue screen show. This minimizes the "flash" effect as the first react-native screen I shows matches the below background color i set in AppDelegate.m
`rootView.backgroundColor = [[UIColor alloc] initWithRed:1.0f green:1.0f blue:1.0f alpha:1];`

**Comment by baselbj** [comment]
me also having the same issue

**Comment by Kalyani518** [comment]
same issue
