### ISSUE TITLE
Crash on iOS 13

### ISSUE THREAD

**Issue by kyhnlbyrk** [crazycodeboy/react-native-splash-screen#447]
Run `react-native info` in your project and share the content.

>  System:
      OS: macOS 10.14.4
      CPU: (4) x64 Intel(R) Core(TM) i5-5350U CPU @ 1.80GHz
      Memory: 22.82 MB / 8.00 GB
      Shell: 3.2.57 - /bin/bash
    Binaries:
      Node: 8.11.2 - /usr/local/bin/node
      npm: 6.4.1 - /usr/local/bin/npm
      Watchman: 4.9.0 - /usr/local/bin/watchman
    SDKs:
      iOS SDK:
        Platforms: iOS 13.2, DriverKit 19.0, macOS 10.15, tvOS 13.2, watchOS 6.1
      Android SDK:
        API Levels: 26, 27, 28
        Build Tools: 22.0.1, 23.0.1, 24.0.2, 26.0.0, 26.0.1, 27.0.3, 28.0.1, 28.0.3
        System Images: android-22 | Google APIs Intel x86 Atom, android-24 | Google APIs Intel x86 Atom, android-24 | Google Play Intel x86 Atom
    IDEs:
      Xcode: 11.2.1/11B500 - /usr/bin/xcodebuild
    npmPackages:
      react: 16.6.3 => 16.6.3 
      react-native: 0.59.3 => 0.59.3 
    npmGlobalPackages:
      create-react-native-app: 1.0.0
      react-native-cli: 2.0.1
      react-native-git-upgrade: 0.2.7

What `react-native-splash-screen` version are you using? **3.2.0**

What platform does your issue occur on? (Android/iOS/Both) **iOS**

Describe your issue as precisely as possible : 
  1) Steps to reproduce the issue or to explain in which case you get the issue

The app is crashing on startup. At this line of code
`[[NSRunLoop mainRunLoop] runUntilDate:later];` 
in show function
  2) Interesting `logs`

> reason: 'Exception '*** -[__NSArrayM objectAtIndexedSubscript:]: index 1 beyond bounds [0 .. 0]' was thrown while invoking getInitialURL on target LinkingManager with params (
    56,
...'
*** First throw call stack:
(0x19d7d580c 0x19d4fdfa4 0x102bcc03c 0x102c1c700 0x102c1c290 0x10358d7fc 0x10358ebd8 0x10359cc34 0x19d7533a8 0x19d74e39c 0x19d74d8a0 0x19da8d824 0x19da8d704 0x102ba2c1c 0x102a9705c 0x1a1834ef4 0x1a1836d20 0x1a183c554 0x1a100acdc 0x1a149ffc4 0x1a100b7c4 0x1a100b21c 0x1a100b5f0 0x1a100aeac 0x1a100f3c8 0x1a13d26a4 0x1a14b95b0 0x1a100f100 0x1a14b94ac 0x1a100ef6c 0x1a0e80ba4 0x1a0e7f70c 0x1a0e808dc 0x1a183a8d4 0x1a13f309c 0x1a28da850 0x1a28ff8e8 0x1a28e4fb4 0x1a28ff5a4 0x10358ebd8 0x103591ffc 0x1a29244c8 0x1a2924194 0x1a29246bc 0x19d7537c4 0x19d75371c 0x19d752eb4 0x19d74e000 0x19d74d8a0 0x1a76a5328 0x1a183e768 0x102a9711c 0x19d5d8360)
libc++abi.dylib: terminating with uncaught exception of type NSException

Join a screenshot or video of the problem on the simulator or device?

It crashes and stuck at the splash screen

**Comment by lucasOlivio** [comment]
Hy @kyhnlbyrk , I known it has been a long time, but I'm having the same problems here. Did you manage to fix it?

Here is my log: 

`2020-02-06 13:35:41.812 [info][tid:main][RCTCxxBridge.mm:236] Initializing <RCTCxxBridge: 0x1065006a0> (parent: <RCTBridge: 0x2832af6b0>, executor: (null))
2020-02-06 13:35:41.889 [warn][tid:main][RCTModuleData.mm:67] Module AudioRecorderManager requires main queue setup since it overrides `constantsToExport` but doesn't implement `requiresMainQueueSetup`. In a future release React Native will default to initializing all native modules on a background thread unless explicitly opted-out of.
2020-02-06 13:35:41.890 [warn][tid:main][RCTModuleData.mm:67] Module RNRealmPath requires main queue setup since it overrides `constantsToExport` but doesn't implement `requiresMainQueueSetup`. In a future release React Native will default to initializing all native modules on a background thread unless explicitly opted-out of.
2020-02-06 13:35:41.890 [warn][tid:main][RCTModuleData.mm:67] Module ReactNativeShareExtension requires main queue setup since it overrides `init` but doesn't implement `requiresMainQueueSetup`. In a future release React Native will default to initializing all native modules on a background thread unless explicitly opted-out of.
2020-02-06 13:35:41.946 [info][tid:main][RCTRootView.m:293] Running application DVinvest ({
    initialProps =     {
    };
    rootTag = 1;
})
2020-02-06 13:35:43.146 [warn][tid:NSOperationQueue 0x10610ae60 (QOS: UNSPECIFIED)][RCTModuleData.mm:248] RCTBridge required dispatch_sync to load RCTDevLoadingView. This may lead to deadlocks
libc++abi.dylib: terminating with uncaught exception of type NSException`

and my react-native info:

`
System:
    OS: macOS 10.15.3
    CPU: (4) x64 Intel(R) Core(TM) i5-4250U CPU @ 1.30GHz
    Memory: 40.00 MB / 4.00 GB
    Shell: 3.2.57 - /bin/bash
  Binaries:
    Node: 10.18.1 - /usr/local/opt/node@10/bin/node
    Yarn: 1.21.1 - /usr/local/bin/yarn
    npm: 6.13.4 - /usr/local/opt/node@10/bin/npm
    Watchman: 4.9.0 - /usr/local/bin/watchman
  SDKs:
    iOS SDK:
      Platforms: iOS 13.2, DriverKit 19.0, macOS 10.15, tvOS 13.2, watchOS 6.1
  IDEs:
    Xcode: 11.3.1/11C504 - /usr/bin/xcodebuild
  npmPackages:
    react: 16.8.6 => 16.8.6 
    react-native: 0.60.4 => 0.60.4
`

**Comment by figureai** [comment]
I encountered the same problem

**Comment by figureai** [comment]
I get the same problem on iOS13.3.1

**Comment by figureai** [comment]
@lucasOlivio @kyhnlbyrk  this way make my project work:
https://medium.com/@igniz87/react-native-unknown-argument-type-attribute-in-method-rctappstate-5daf904b2367

**Comment by lucasOlivio** [comment]
@figureai  tnx for the reply, but I just changed the lib

**Comment by anastely** [comment]
@lucasOlivio  Wahts Lib you used?

**Comment by bluetrade-invest** [comment]
@anastely I used react-native-bootsplash, its working fine so far.

**Comment by lucasOlivio** [comment]
@anastely I used react-native-bootsplash. Working fine so far
