### ISSUE TITLE
Question: why use this library in iOS instead of default splashscreen settings

### ISSUE THREAD

**Issue by jsdario** [crazycodeboy/react-native-splash-screen#72]
Hi!

I am using this library in Android and it works like a charm. I wonder if it is any good to actually use the library in iOS or I should keep using my splashscreen configuration.

Thanks

**Comment by NSLS** [comment]
I am personally using this library on iOS for app preloading. Generally, iOS hides the splash screen as soon as your app is initialized, but in many cases you would want to run some other code, e.g. authentication, in order to preload the auth state and set the appropriate initial screen before hiding the splash screen

**Comment by jsdario** [comment]
Cool, thanks!
